/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DatenschutzIndexRouteImport } from './routes/Datenschutz/index'
import { Route as ProfilIdRouteImport } from './routes/Profil/$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzIndexRoute = DatenschutzIndexRouteImport.update({
  id: '/Datenschutz/',
  path: '/Datenschutz/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilIdRoute = ProfilIdRouteImport.update({
  id: '/Profil/$id',
  path: '/Profil/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Profil/$id': typeof ProfilIdRoute
  '/Datenschutz': typeof DatenschutzIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Profil/$id': typeof ProfilIdRoute
  '/Datenschutz': typeof DatenschutzIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/Profil/$id': typeof ProfilIdRoute
  '/Datenschutz/': typeof DatenschutzIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/Profil/$id' | '/Datenschutz' | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/Profil/$id' | '/Datenschutz' | '/api/auth/$'
  id: '__root__' | '/' | '/Profil/$id' | '/Datenschutz/' | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProfilIdRoute: typeof ProfilIdRoute
  DatenschutzIndexRoute: typeof DatenschutzIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Datenschutz/': {
      id: '/Datenschutz/'
      path: '/Datenschutz'
      fullPath: '/Datenschutz'
      preLoaderRoute: typeof DatenschutzIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Profil/$id': {
      id: '/Profil/$id'
      path: '/Profil/$id'
      fullPath: '/Profil/$id'
      preLoaderRoute: typeof ProfilIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProfilIdRoute: ProfilIdRoute,
  DatenschutzIndexRoute: DatenschutzIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
